#!/bin/bash

#check if a fullscreen window is open

while true; do
    fullscreen_window_id=$(xprop -root _NET_ACTIVE_WINDOW | awk '{print $5}')
    class=$(xprop -id $fullscreen_window_id WM_CLASS | rev | cut -c 3- | rev | cut -c 19-)


	 if [[ $class == *"Firefox"* ]]; then
        	# Check if the window is in fullscreen state
		state=$(xprop -id $fullscreen_window_id _NET_WM_STATE | grep _NET_WM_STATE_FULLSCREEN)
		if [[ "$state" != "" ]]; then
			# Hide Polybar
		        polybar-msg cmd hide
		        sleep 1
	fi
	fi 
       		if [[ $class == *"mpv"* ]]; then
        	# Hide Polybar
       		 polybar-msg cmd hide
	        sleep 1
         fi
    sleep 1
done

